# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialTracksApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SocialTracksApp
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [ 'Core', 'CxxBridge', 'DevSupport', 'RCTText', 'RCTImage', 'RCTNetwork', 'RCTWebSocket']
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'SocialTracksAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SocialTracksApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SocialTracksApp-tvOS

  target 'SocialTracksApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
